### PR TITLE
Implementation of front end

### PR DESCRIPTION
**Pull request by peter-strizhev**
Implemented a front end and python interface using Node.js for your code, edit the budgetCalculator.py file to do your calculations. I included a simple front-end for my example function. Once you have more in the python file, I will update this code to have user logins and cloud integration once you have that set up on your end. I also included a screenshot of the front end in case youre having trouble running it.
budgetCalcUI

### CODE REVIEW

**Comment by peter-strizhev** [comment]
LMK if you have an questions on running this, you will have to set up node.js on your local machine, but a run file is already included in the .vscode file called launch.js

**Comment by amielterry26** [comment]
Cool bro. You work today?

*Amiel Terry *
*Web Developer + ​S​oftware Engineer*
*F**OUNDER* of ​1000dollarwebsies.co
(725)-285-5684
AmielTerry Dev.

**Comment by peter-strizhev** [comment]
I don't today, but I work tomorrow through Monday.

**Comment by amielterry26** [comment]
Bet. I’ll be here some of those days too.
Let’s chat bout some ideas

*Amiel Terry *
*Web Developer + ​S​oftware Engineer*
*F**OUNDER* of ​1000dollarwebsies.co
(725)-285-5684
AmielTerry Dev.

**Pull request merged**
